apiVersion: apps/v1
kind: Deployment                                          # 资源类型
metadata:
  name: ember-app-deployment
spec:
  replicas: 2                                             # pod 副本数量
  minReadySeconds: 15
  selector:
    matchLabels:
      app: ember-app
  strategy:
    type: RollingUpdate                                   # 部署策略 滚动升级
    rollingUpdate: 
      maxUnavailable: 1                                   # 在升级过程中最多允许几个 pod 不可用
      maxSurge: 1                                         # 升级过程中允许最多添加几个 pod, 如果 副本是 2 升级过程中要保证可用一直是 2 必须要再加一个 pod
  template:                                               # 定义 deploy 使用 pod
    metadata:
      labels:
        app: ember-app                                  #  模板定的 pod 的 label 根据这个 label 生成 service
    spec:                                               # spec 相当于 step-one 中的 pod
      containers:
        - image: zhyq0826/nginx:k8s-ember-app
          imagePullPolicy: Always                         # 镜像策略
          name: ember-app
          ports:
            - containerPort: 80