apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: python-app
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - image: zhyq0826/python:k8s-python-app
          imagePullPolicy: Always
          name: python-app
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-service.default.svc.cluster.local   # 利用 k8s 提供的默认 dns 解析，发现 redis 服务